/* 
Problem: The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
What is the value of the first triangle number to have over five hundred divisors?
*/ 

using System;
using System.Collections.Generic;
using System.Linq; 
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication56
{
    class Program
    {
        public static int count_divisors(int num)
        {
            int i = 1;
            int count = 0;
            while (i <= num)
            {
                if (num % i == 0)
                {
                    count++; 
                }

                i++;
            }
            return count;
        }

        public static IEnumerable<int> getFactors(int x)
        {
            for (int i = 1; i * i <= x; i++)
            {
                if ((x % i) == 0)
                {
                    yield return i;
                    if (i != (x / i))
                    {
                        yield return x / i;
                    }
                }
            }
        }

        public static void Main(string[] args)
        {
            int count = 28; 
            int i = 8; 
            do
            {
                count += i;
                i++;
            }
            while (getFactors(count).Cast<Object>().Count() <= 500);
            Console.WriteLine(count);
            Console.ReadLine(); 
            return; 
        }
    }
}
