/* 
Problem: How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/ 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics; 
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication61
{
    class Program
    {
        public static int count_digit(BigInteger num)
        {
            string long_str = num.ToString();
            return long_str.Length; 
        } 

        public static void Main(string[] args)
        {
            List<double> pow_list = new List<double>(); 
            for (int a = 2; a <= 100; a++)
            {
                for(int b = 2; b <= 100; b++)
                {
                    pow_list.Add(Math.Pow(a, b)); 
                }
            }
            pow_list = pow_list.Distinct().ToList(); 
            pow_list.Sort();
            Console.WriteLine(pow_list.Count());
            Console.ReadLine(); 
            return; 
        }
    }
}


